# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f287d4dab1f32902dc21d1752035aa0be28478c75b2545607876dc5ad956972b2891eace3ee1d0a1881a57952b0d83238bb16595a7337886515d5f583a2a99b6

test:
  secret_key_base: ecd29199f38ec6ab21f6d7147facf4f3d8882cdf69ae8a5c80a13e068067e66ea665a99b247b3ee1339e12f1c30ea2c2e5c266c9f53bac573b38ac8f24b7a45d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
